// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa6XRvqVGjm8vPy29kITEdhhMsUsVjwdw',
    appId: '1:331303996125:web:f31f6dabec07a28755e934',
    messagingSenderId: '331303996125',
    projectId: 'flutter-app-187cb',
    authDomain: 'flutter-app-187cb.firebaseapp.com',
    storageBucket: 'flutter-app-187cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNQQ_3cYRnvjBJqjbaDGYEAauHKeqf2Tw',
    appId: '1:331303996125:android:ceba6faf6a76348b55e934',
    messagingSenderId: '331303996125',
    projectId: 'flutter-app-187cb',
    storageBucket: 'flutter-app-187cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATiJ2hOYIZAHEKYdQdHy2KMi5flb894Dg',
    appId: '1:331303996125:ios:ac54a93d7cd97ba955e934',
    messagingSenderId: '331303996125',
    projectId: 'flutter-app-187cb',
    storageBucket: 'flutter-app-187cb.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATiJ2hOYIZAHEKYdQdHy2KMi5flb894Dg',
    appId: '1:331303996125:ios:2fecb639aff1dd9a55e934',
    messagingSenderId: '331303996125',
    projectId: 'flutter-app-187cb',
    storageBucket: 'flutter-app-187cb.appspot.com',
    iosBundleId: 'com.example.flutterApp.RunnerTests',
  );
}
